//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRAYARLAR
    {
        public int AYARLAROGRID { get; set; }
        public string OGRSIFRE { get; set; }
    
        public virtual TBL_OGRENCILER TBL_OGRENCILER { get; set; }
    }
}
